[alias]
c = """
clippy --all-targets --all-features -- 
-W clippy::pedantic 
-W clippy::nursery
-W clippy::cargo
-D clippy::unwrap_used
-A clippy::too_many_arguments 
-A clippy::cargo_common_metadata 
-A clippy::multiple_crate_versions
-A clippy::too_many_lines
-A clippy::default_trait_access
-A clippy::trivially_copy_pass_by_ref
-A clippy::items_after_statements
-A clippy::cast_possible_truncation
-A clippy::cast_precision_loss
"""

[build]
rustflags = ["--cfg=web_sys_unstable_apis"]

[env]
RUST_LOG = "info"
